/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formilario;

import com.sun.awt.AWTUtilities;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;

/**
 *
 * @author jrivoinp
 */
public class FormularioPersonalizado extends javax.swing.JFrame {

    /**
     * Creates new form FormularioPersonalizado
     */
    boolean infobtn , nuevobtn ;
    int x,y;
    CardLayout card ;
    public FormularioPersonalizado() {
        initComponents();
        this.setLocationRelativeTo(null);
        AWTUtilities.setWindowOpaque(this, false);
        
        infobtn = nuevobtn = false ;
        
        Paneles( false );
        PanelInformacio.setVisible(true);
        // Centrar Titulo de Tabla
        JTableHeader jtableHeader = Tabla.getTableHeader();
        DefaultTableCellRenderer rend = (DefaultTableCellRenderer) Tabla.getTableHeader().getDefaultRenderer();
        rend.setHorizontalAlignment(JLabel.CENTER);
        jtableHeader.setDefaultRenderer(rend);
        
        
			
        // Transparencia a Tabla
        Tabla.setOpaque(false);
        Tabla.setBackground(new Color(0, 0, 0, 0));
        jScrollPane1.getViewport().setOpaque(false);
        jScrollPane1.setOpaque(false);
        
        // Centrar columnas de Tabla 
        DefaultTableCellRenderer modelocentrar = new DefaultTableCellRenderer();
        modelocentrar.setHorizontalAlignment(SwingConstants.CENTER);
        Tabla.getColumnModel().getColumn(0).setCellRenderer(modelocentrar); 
        Tabla.getColumnModel().getColumn(1).setCellRenderer(modelocentrar);
        Tabla.getColumnModel().getColumn(2).setCellRenderer(modelocentrar);
        Tabla.getColumnModel().getColumn(4).setCellRenderer(modelocentrar);
        
        
    }
    
   

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
           getImage(ClassLoader.getSystemResource("Imagenes/Rivoin.png"));
        return retValue;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelGeneral = new javax.swing.JPanel();
        InformacionBtn = new javax.swing.JButton();
        NuevoBtn = new javax.swing.JButton();
        PanelConsulta = new javax.swing.JPanel();
        SalirConsulta = new javax.swing.JButton();
        numeropanel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        titulo1 = new javax.swing.JLabel();
        PanelInformacio = new javax.swing.JPanel();
        instagram = new javax.swing.JButton();
        twitter = new javax.swing.JButton();
        facebook = new javax.swing.JButton();
        Peru = new javax.swing.JLabel();
        titulo2 = new javax.swing.JLabel();
        PanelUsuarios = new javax.swing.JPanel();
        SalirUsuario = new javax.swing.JButton();
        numeropanel1 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        NombreCompletoTxt = new javax.swing.JTextField();
        icono = new javax.swing.JLabel();
        fondotexto = new javax.swing.JLabel();
        DocumentoIdentidadTxt = new javax.swing.JTextField();
        icono1 = new javax.swing.JLabel();
        fondotexto1 = new javax.swing.JLabel();
        Celulartxt = new javax.swing.JTextField();
        icono2 = new javax.swing.JLabel();
        fondotexto2 = new javax.swing.JLabel();
        Usuariotxt = new javax.swing.JTextField();
        icono3 = new javax.swing.JLabel();
        fondotexto3 = new javax.swing.JLabel();
        PanelPanelUsuario = new javax.swing.JPanel();
        AgregarBtn = new javax.swing.JButton();
        ModificarBtn = new javax.swing.JButton();
        AgregarBtn3 = new javax.swing.JButton();
        LimpiarBtn1 = new javax.swing.JButton();
        LimpiarBtn = new javax.swing.JButton();
        ContraseñatxtUsuario = new javax.swing.JTextField();
        icono4 = new javax.swing.JLabel();
        fondotexto4 = new javax.swing.JLabel();
        PanelBotones = new javax.swing.JPanel();
        SalirSystem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formulario");
        setIconImage(getIconImage());
        setUndecorated(true);
        setResizable(false);

        PanelGeneral.setBackground(new java.awt.Color(51, 149, 214));
        PanelGeneral.setPreferredSize(new java.awt.Dimension(650, 450));
        PanelGeneral.setLayout(null);

        InformacionBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Diseño Proyecto.png"))); // NOI18N
        InformacionBtn.setBorder(null);
        InformacionBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        InformacionBtn.setFocusPainted(false);
        InformacionBtn.setFocusable(false);
        InformacionBtn.setOpaque(false);
        InformacionBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InformacionBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InformacionBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InformacionBtnMouseExited(evt);
            }
        });
        PanelGeneral.add(InformacionBtn);
        InformacionBtn.setBounds(-175, 20, 230, 60);

        NuevoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Reporte.png"))); // NOI18N
        NuevoBtn.setBorder(null);
        NuevoBtn.setBorderPainted(false);
        NuevoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NuevoBtn.setFocusPainted(false);
        NuevoBtn.setFocusable(false);
        NuevoBtn.setOpaque(false);
        NuevoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NuevoBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NuevoBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NuevoBtnMouseExited(evt);
            }
        });
        PanelGeneral.add(NuevoBtn);
        NuevoBtn.setBounds(-175, 90, 230, 60);

        PanelConsulta.setBackground(new java.awt.Color(51, 149, 214));
        PanelConsulta.setLayout(null);

        SalirConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-xbox-x-filled-30.png"))); // NOI18N
        SalirConsulta.setBorder(null);
        SalirConsulta.setBorderPainted(false);
        SalirConsulta.setContentAreaFilled(false);
        SalirConsulta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SalirConsulta.setDefaultCapable(false);
        SalirConsulta.setFocusPainted(false);
        SalirConsulta.setFocusable(false);
        SalirConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirConsultaActionPerformed(evt);
            }
        });
        PanelConsulta.add(SalirConsulta);
        SalirConsulta.setBounds(520, 0, 60, 60);

        numeropanel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        numeropanel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numeropanel2.setText("2");
        PanelConsulta.add(numeropanel2);
        numeropanel2.setBounds(700, 0, 30, 40);

        jScrollPane1.setBackground(new java.awt.Color(51, 149, 214));
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setEnabled(false);
        jScrollPane1.setFocusable(false);
        jScrollPane1.setOpaque(false);

        Tabla.setAutoCreateRowSorter(true);
        Tabla.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Tabla.setForeground(new java.awt.Color(255, 255, 255));
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Rivoin", "123", "Juan Rivoin", "999 999 999"},
                {"2", "Bar", "111", "Bar Simpson", "999 888 888"},
                {"3", "Meliodas", "777", "Meliodas Pecado", "999 777 777"}
            },
            new String [] {
                "N°", "Usuario", "Contraseña", "Nombre y Apellidos", "Celular"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabla.setAlignmentX(1.0F);
        Tabla.setAlignmentY(1.0F);
        Tabla.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Tabla.setEnabled(false);
        Tabla.setFocusable(false);
        Tabla.setGridColor(new java.awt.Color(26, 188, 156));
        Tabla.setOpaque(false);
        Tabla.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(Tabla);

        PanelConsulta.add(jScrollPane1);
        jScrollPane1.setBounds(2, 62, 580, 390);

        titulo1.setFont(new java.awt.Font("Claudia", 3, 36)); // NOI18N
        titulo1.setForeground(new java.awt.Color(255, 255, 255));
        titulo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titulo1.setText("Reporte Usuarios");
        PanelConsulta.add(titulo1);
        titulo1.setBounds(10, 10, 280, 40);

        PanelGeneral.add(PanelConsulta);
        PanelConsulta.setBounds(60, 0, 730, 450);

        PanelInformacio.setBackground(new java.awt.Color(51, 149, 214));
        PanelInformacio.setLayout(null);

        instagram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-instagram-filled-30.png"))); // NOI18N
        instagram.setBorder(null);
        instagram.setBorderPainted(false);
        instagram.setContentAreaFilled(false);
        instagram.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        instagram.setDefaultCapable(false);
        instagram.setFocusPainted(false);
        instagram.setFocusable(false);
        instagram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instagramActionPerformed(evt);
            }
        });
        PanelInformacio.add(instagram);
        instagram.setBounds(390, 120, 40, 40);

        twitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-twitter-filled-30.png"))); // NOI18N
        twitter.setBorder(null);
        twitter.setBorderPainted(false);
        twitter.setContentAreaFilled(false);
        twitter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        twitter.setDefaultCapable(false);
        twitter.setFocusPainted(false);
        twitter.setFocusable(false);
        twitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twitterActionPerformed(evt);
            }
        });
        PanelInformacio.add(twitter);
        twitter.setBounds(270, 120, 40, 40);

        facebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-facebook-30.png"))); // NOI18N
        facebook.setBorder(null);
        facebook.setBorderPainted(false);
        facebook.setContentAreaFilled(false);
        facebook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        facebook.setDefaultCapable(false);
        facebook.setFocusPainted(false);
        facebook.setFocusable(false);
        facebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facebookActionPerformed(evt);
            }
        });
        PanelInformacio.add(facebook);
        facebook.setBounds(140, 120, 40, 40);

        Peru.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Peru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-perú-30.png"))); // NOI18N
        PanelInformacio.add(Peru);
        Peru.setBounds(250, 190, 68, 30);

        titulo2.setFont(new java.awt.Font("Colonna MT", 3, 36)); // NOI18N
        titulo2.setForeground(new java.awt.Color(255, 255, 255));
        titulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo2.setText("Rivoin");
        titulo2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                titulo2MouseDragged(evt);
            }
        });
        PanelInformacio.add(titulo2);
        titulo2.setBounds(0, 60, 590, 40);

        PanelGeneral.add(PanelInformacio);
        PanelInformacio.setBounds(60, 0, 590, 450);

        PanelUsuarios.setBackground(new java.awt.Color(51, 149, 214));
        PanelUsuarios.setPreferredSize(new java.awt.Dimension(590, 450));
        PanelUsuarios.setLayout(null);

        SalirUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-xbox-x-filled-30.png"))); // NOI18N
        SalirUsuario.setBorder(null);
        SalirUsuario.setBorderPainted(false);
        SalirUsuario.setContentAreaFilled(false);
        SalirUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SalirUsuario.setDefaultCapable(false);
        SalirUsuario.setFocusPainted(false);
        SalirUsuario.setFocusable(false);
        SalirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirUsuarioActionPerformed(evt);
            }
        });
        PanelUsuarios.add(SalirUsuario);
        SalirUsuario.setBounds(520, 0, 60, 60);

        numeropanel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        numeropanel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numeropanel1.setText("1");
        PanelUsuarios.add(numeropanel1);
        numeropanel1.setBounds(730, 0, 30, 40);

        titulo.setFont(new java.awt.Font("Claudia", 3, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titulo.setText("Registrar Usuarios");
        PanelUsuarios.add(titulo);
        titulo.setBounds(10, 10, 280, 40);

        NombreCompletoTxt.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        NombreCompletoTxt.setForeground(new java.awt.Color(72, 124, 162));
        NombreCompletoTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NombreCompletoTxt.setText("Nombre Completo de Usuario");
        NombreCompletoTxt.setBorder(null);
        NombreCompletoTxt.setOpaque(false);
        NombreCompletoTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NombreCompletoTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                NombreCompletoTxtFocusLost(evt);
            }
        });
        PanelUsuarios.add(NombreCompletoTxt);
        NombreCompletoTxt.setBounds(50, 60, 460, 40);

        icono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user.png"))); // NOI18N
        PanelUsuarios.add(icono);
        icono.setBounds(20, 60, 30, 40);

        fondotexto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/txt_largo.png"))); // NOI18N
        PanelUsuarios.add(fondotexto);
        fondotexto.setBounds(10, 60, 520, 40);

        DocumentoIdentidadTxt.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        DocumentoIdentidadTxt.setForeground(new java.awt.Color(72, 124, 162));
        DocumentoIdentidadTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DocumentoIdentidadTxt.setText("Documento de Identidad");
        DocumentoIdentidadTxt.setBorder(null);
        DocumentoIdentidadTxt.setOpaque(false);
        DocumentoIdentidadTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DocumentoIdentidadTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                DocumentoIdentidadTxtFocusLost(evt);
            }
        });
        PanelUsuarios.add(DocumentoIdentidadTxt);
        DocumentoIdentidadTxt.setBounds(50, 110, 190, 40);

        icono1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icono1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-tarjeta-de-contacto-20.png"))); // NOI18N
        PanelUsuarios.add(icono1);
        icono1.setBounds(20, 110, 30, 40);

        fondotexto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/txt_med.png"))); // NOI18N
        PanelUsuarios.add(fondotexto1);
        fondotexto1.setBounds(10, 110, 240, 40);

        Celulartxt.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        Celulartxt.setForeground(new java.awt.Color(72, 124, 162));
        Celulartxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Celulartxt.setText("Celular");
        Celulartxt.setBorder(null);
        Celulartxt.setOpaque(false);
        Celulartxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CelulartxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                CelulartxtFocusLost(evt);
            }
        });
        Celulartxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CelulartxtKeyTyped(evt);
            }
        });
        PanelUsuarios.add(Celulartxt);
        Celulartxt.setBounds(340, 110, 180, 40);

        icono2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icono2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-iphone-20.png"))); // NOI18N
        PanelUsuarios.add(icono2);
        icono2.setBounds(305, 110, 30, 40);

        fondotexto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/txt_med.png"))); // NOI18N
        PanelUsuarios.add(fondotexto2);
        fondotexto2.setBounds(295, 110, 240, 40);

        Usuariotxt.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        Usuariotxt.setForeground(new java.awt.Color(72, 124, 162));
        Usuariotxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Usuariotxt.setText("Usuario");
        Usuariotxt.setBorder(null);
        Usuariotxt.setOpaque(false);
        Usuariotxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UsuariotxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                UsuariotxtFocusLost(evt);
            }
        });
        PanelUsuarios.add(Usuariotxt);
        Usuariotxt.setBounds(60, 170, 180, 40);

        icono3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icono3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user.png"))); // NOI18N
        PanelUsuarios.add(icono3);
        icono3.setBounds(20, 170, 30, 40);

        fondotexto3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/txt_med.png"))); // NOI18N
        PanelUsuarios.add(fondotexto3);
        fondotexto3.setBounds(10, 170, 240, 40);

        PanelPanelUsuario.setBackground(new java.awt.Color(255, 255, 255));
        PanelPanelUsuario.setLayout(null);

        AgregarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-administrador-del-hombre-50.png"))); // NOI18N
        AgregarBtn.setBorder(null);
        AgregarBtn.setBorderPainted(false);
        AgregarBtn.setContentAreaFilled(false);
        AgregarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AgregarBtn.setDefaultCapable(false);
        AgregarBtn.setFocusPainted(false);
        AgregarBtn.setFocusable(false);
        PanelPanelUsuario.add(AgregarBtn);
        AgregarBtn.setBounds(100, 10, 60, 60);

        ModificarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-editar-propiedad-filled-50.png"))); // NOI18N
        ModificarBtn.setBorder(null);
        ModificarBtn.setBorderPainted(false);
        ModificarBtn.setContentAreaFilled(false);
        ModificarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ModificarBtn.setDefaultCapable(false);
        ModificarBtn.setFocusPainted(false);
        ModificarBtn.setFocusable(false);
        PanelPanelUsuario.add(ModificarBtn);
        ModificarBtn.setBounds(170, 10, 60, 60);

        AgregarBtn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-búsqueda-filled-50.png"))); // NOI18N
        AgregarBtn3.setBorder(null);
        AgregarBtn3.setBorderPainted(false);
        AgregarBtn3.setContentAreaFilled(false);
        AgregarBtn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AgregarBtn3.setDefaultCapable(false);
        AgregarBtn3.setFocusPainted(false);
        AgregarBtn3.setFocusable(false);
        PanelPanelUsuario.add(AgregarBtn3);
        AgregarBtn3.setBounds(240, 10, 60, 60);

        LimpiarBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-eliminar-filled-50.png"))); // NOI18N
        LimpiarBtn1.setBorder(null);
        LimpiarBtn1.setBorderPainted(false);
        LimpiarBtn1.setContentAreaFilled(false);
        LimpiarBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LimpiarBtn1.setDefaultCapable(false);
        LimpiarBtn1.setFocusPainted(false);
        LimpiarBtn1.setFocusable(false);
        PanelPanelUsuario.add(LimpiarBtn1);
        LimpiarBtn1.setBounds(310, 10, 60, 60);

        LimpiarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-escoba-filled-50.png"))); // NOI18N
        LimpiarBtn.setBorder(null);
        LimpiarBtn.setBorderPainted(false);
        LimpiarBtn.setContentAreaFilled(false);
        LimpiarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LimpiarBtn.setDefaultCapable(false);
        LimpiarBtn.setFocusPainted(false);
        LimpiarBtn.setFocusable(false);
        PanelPanelUsuario.add(LimpiarBtn);
        LimpiarBtn.setBounds(370, 10, 60, 60);

        PanelUsuarios.add(PanelPanelUsuario);
        PanelPanelUsuario.setBounds(0, 380, 630, 70);

        ContraseñatxtUsuario.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        ContraseñatxtUsuario.setForeground(new java.awt.Color(72, 124, 162));
        ContraseñatxtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ContraseñatxtUsuario.setText("Contraseña");
        ContraseñatxtUsuario.setToolTipText("");
        ContraseñatxtUsuario.setBorder(null);
        ContraseñatxtUsuario.setOpaque(false);
        ContraseñatxtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ContraseñatxtUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ContraseñatxtUsuarioFocusLost(evt);
            }
        });
        PanelUsuarios.add(ContraseñatxtUsuario);
        ContraseñatxtUsuario.setBounds(340, 170, 180, 40);

        icono4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icono4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-candado-2-filled-20.png"))); // NOI18N
        PanelUsuarios.add(icono4);
        icono4.setBounds(310, 170, 20, 40);

        fondotexto4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/txt_med.png"))); // NOI18N
        PanelUsuarios.add(fondotexto4);
        fondotexto4.setBounds(295, 170, 240, 40);

        PanelGeneral.add(PanelUsuarios);
        PanelUsuarios.setBounds(60, 0, 760, 450);

        PanelBotones.setBackground(new java.awt.Color(26, 188, 156));
        PanelBotones.setPreferredSize(new java.awt.Dimension(20, 450));
        PanelBotones.setLayout(null);

        SalirSystem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-apagar-filled-50.png"))); // NOI18N
        SalirSystem.setBorder(null);
        SalirSystem.setBorderPainted(false);
        SalirSystem.setContentAreaFilled(false);
        SalirSystem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SalirSystem.setDefaultCapable(false);
        SalirSystem.setFocusPainted(false);
        SalirSystem.setFocusable(false);
        SalirSystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirSystemActionPerformed(evt);
            }
        });
        PanelBotones.add(SalirSystem);
        SalirSystem.setBounds(0, 390, 60, 60);

        PanelGeneral.add(PanelBotones);
        PanelBotones.setBounds(0, 0, 60, 450);

        getContentPane().add(PanelGeneral, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void InformacionBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InformacionBtnMouseEntered
        if ( !infobtn ) {
            Animacion.Animacion.mover_derecha( -175 , 0 , 1 , 2 , InformacionBtn );
        }
    }//GEN-LAST:event_InformacionBtnMouseEntered

    private void InformacionBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InformacionBtnMouseExited
        if ( !infobtn ) {
            Animacion.Animacion.mover_izquierda( 0 , -175 , 1 , 2 , InformacionBtn );
        }
    }//GEN-LAST:event_InformacionBtnMouseExited

    private void NuevoBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NuevoBtnMouseEntered
        if ( !nuevobtn ) {
            Animacion.Animacion.mover_derecha( -175 , 0 , 1 , 2 , NuevoBtn );
        }
    }//GEN-LAST:event_NuevoBtnMouseEntered

    private void NuevoBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NuevoBtnMouseExited
        if ( !nuevobtn ) {
            Animacion.Animacion.mover_izquierda( 0 , -175 , 1 , 2 , NuevoBtn );
        }
    }//GEN-LAST:event_NuevoBtnMouseExited

    private void SalirSystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirSystemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirSystemActionPerformed

    private void InformacionBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InformacionBtnMouseClicked
        Paneles( false );
        PanelUsuarios.setVisible( true );
    }//GEN-LAST:event_InformacionBtnMouseClicked

    private void NuevoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NuevoBtnMouseClicked
        Paneles( false );
        PanelConsulta.setVisible( true );
    }//GEN-LAST:event_NuevoBtnMouseClicked

    private void DocumentoIdentidadTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DocumentoIdentidadTxtFocusGained
        if ( DocumentoIdentidadTxt . getText () . trim() . equals ( "Documento de Identidad" ) ) {
            DocumentoIdentidadTxt.setText ("");
            DocumentoIdentidadTxt.setForeground (new Color(0,64,255));
        }
    }//GEN-LAST:event_DocumentoIdentidadTxtFocusGained

    private void DocumentoIdentidadTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DocumentoIdentidadTxtFocusLost
        if ( DocumentoIdentidadTxt . getText (). trim (). equals ("") ) {
            DocumentoIdentidadTxt.setText ("Documento de Identidad");
            DocumentoIdentidadTxt.setForeground (new Color (72,124,162));
        }
    }//GEN-LAST:event_DocumentoIdentidadTxtFocusLost

    private void NombreCompletoTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NombreCompletoTxtFocusGained
        if ( NombreCompletoTxt . getText () . trim() . equals ( "Nombre Completo de Usuario" ) ) {
            NombreCompletoTxt.setText ("");
            NombreCompletoTxt.setForeground (new Color(0,64,255));
        }
    }//GEN-LAST:event_NombreCompletoTxtFocusGained

    private void NombreCompletoTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NombreCompletoTxtFocusLost
        if ( NombreCompletoTxt . getText (). trim (). equals ("") ) {
            NombreCompletoTxt.setText ("Nombre Completo de Usuario");
            NombreCompletoTxt.setForeground (new Color (72,124,162));
        }
    }//GEN-LAST:event_NombreCompletoTxtFocusLost

    private void CelulartxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CelulartxtFocusGained
        if ( Celulartxt . getText () . trim() . equals ( "Celular" ) ) {
            Celulartxt.setText ("");
            Celulartxt.setForeground (new Color(0,64,255));
        }
    }//GEN-LAST:event_CelulartxtFocusGained

    private void CelulartxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CelulartxtFocusLost
        if ( Celulartxt . getText (). trim (). equals ("") ) {
            Celulartxt.setText ("Celular");
            Celulartxt.setForeground (new Color (72,124,162));
        }
    }//GEN-LAST:event_CelulartxtFocusLost

    private void CelulartxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CelulartxtKeyTyped
        char car = evt.getKeyChar();
        if(car < '0' || car > '9') evt.consume();
    }//GEN-LAST:event_CelulartxtKeyTyped

    private void UsuariotxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsuariotxtFocusGained
        if ( Usuariotxt . getText () . trim() . equals ( "Usuario" ) ) {
            Usuariotxt.setText ("");
            Usuariotxt.setForeground (new Color(0,64,255));
        }
    }//GEN-LAST:event_UsuariotxtFocusGained

    private void UsuariotxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsuariotxtFocusLost
        if ( Usuariotxt . getText (). trim (). equals ("") ) {
            Usuariotxt.setText ("Usuario");
            Usuariotxt.setForeground (new Color (72,124,162));
        }
    }//GEN-LAST:event_UsuariotxtFocusLost

    private void ContraseñatxtUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ContraseñatxtUsuarioFocusGained
        if ( ContraseñatxtUsuario . getText () . trim() . equals ( "Contraseña" ) ) {
            ContraseñatxtUsuario.setText ("");
            ContraseñatxtUsuario.setForeground (new Color(0,64,255));
        }
    }//GEN-LAST:event_ContraseñatxtUsuarioFocusGained

    private void ContraseñatxtUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ContraseñatxtUsuarioFocusLost
        if ( ContraseñatxtUsuario . getText (). trim (). equals ("") ) {
            ContraseñatxtUsuario.setText ("Contraseña");
            ContraseñatxtUsuario.setForeground (new Color (72,124,162));
        }
    }//GEN-LAST:event_ContraseñatxtUsuarioFocusLost

    private void twitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twitterActionPerformed
        try {
            Desktop.getDesktop().browse(new URI( "http://www.twitter.com/JuanRivoin" ) );
        } catch ( URISyntaxException ex) {  System.out.println(ex); } catch (IOException ex) {
            Logger.getLogger(FormularioPersonalizado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_twitterActionPerformed

    private void facebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facebookActionPerformed
        try {
            Desktop.getDesktop().browse(new URI( "http://www.fb.com/RivoxinRx" ) );
        } catch ( URISyntaxException ex) {  System.out.println(ex); } catch (IOException ex) {
            Logger.getLogger(FormularioPersonalizado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_facebookActionPerformed

    private void SalirConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirConsultaActionPerformed
        Paneles( false );
        PanelInformacio.setVisible( true );
    }//GEN-LAST:event_SalirConsultaActionPerformed

    private void SalirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirUsuarioActionPerformed
        Paneles( false );
        PanelInformacio.setVisible( true );
    }//GEN-LAST:event_SalirUsuarioActionPerformed

    private void instagramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instagramActionPerformed
        try {
            Desktop.getDesktop().browse(new URI( "http://www.instagram.com/Rivoin" ) );
        } catch ( URISyntaxException ex) {  System.out.println(ex); } catch (IOException ex) {
            Logger.getLogger(FormularioPersonalizado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_instagramActionPerformed

    private void titulo2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titulo2MouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_titulo2MouseDragged

    public void Paneles ( boolean si ) {
        PanelUsuarios.setVisible( si );
        PanelConsulta.setVisible( si );
        PanelInformacio.setVisible( si );
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioPersonalizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioPersonalizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioPersonalizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioPersonalizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (Exception e) {
                }
                new FormularioPersonalizado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarBtn;
    private javax.swing.JButton AgregarBtn3;
    private javax.swing.JTextField Celulartxt;
    private javax.swing.JTextField ContraseñatxtUsuario;
    private javax.swing.JTextField DocumentoIdentidadTxt;
    private javax.swing.JButton InformacionBtn;
    private javax.swing.JButton LimpiarBtn;
    private javax.swing.JButton LimpiarBtn1;
    private javax.swing.JButton ModificarBtn;
    private javax.swing.JTextField NombreCompletoTxt;
    private javax.swing.JButton NuevoBtn;
    private javax.swing.JPanel PanelBotones;
    private javax.swing.JPanel PanelConsulta;
    private javax.swing.JPanel PanelGeneral;
    private javax.swing.JPanel PanelInformacio;
    private javax.swing.JPanel PanelPanelUsuario;
    private javax.swing.JPanel PanelUsuarios;
    private javax.swing.JLabel Peru;
    private javax.swing.JButton SalirConsulta;
    private javax.swing.JButton SalirSystem;
    private javax.swing.JButton SalirUsuario;
    private javax.swing.JTable Tabla;
    private javax.swing.JTextField Usuariotxt;
    private javax.swing.JButton facebook;
    private javax.swing.JLabel fondotexto;
    private javax.swing.JLabel fondotexto1;
    private javax.swing.JLabel fondotexto2;
    private javax.swing.JLabel fondotexto3;
    private javax.swing.JLabel fondotexto4;
    private javax.swing.JLabel icono;
    private javax.swing.JLabel icono1;
    private javax.swing.JLabel icono2;
    private javax.swing.JLabel icono3;
    private javax.swing.JLabel icono4;
    private javax.swing.JButton instagram;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel numeropanel1;
    private javax.swing.JLabel numeropanel2;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel titulo1;
    private javax.swing.JLabel titulo2;
    private javax.swing.JButton twitter;
    // End of variables declaration//GEN-END:variables
}
