/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formilario;


import com.sun.awt.AWTUtilities;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import javax.swing.Timer;
/**
 *
 * @author jrivoinp
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    
    int x , y , VerContra = 0 , VerIconoContra = 0 , UsuarioExiste = 0;
    Timer timer;
    
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        AWTUtilities.setWindowOpaque(this, false);
        timer = new Timer( 30 , new CargandoBarra());
        setTitle(" Rivoin ");
        progreso.setVisible(false);
        conectandotxt.setVisible(false);
        contratxt.setEchoChar( ( char ) 0 );
        
        
    }
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
           getImage(ClassLoader.getSystemResource("Imagenes/Rivoin.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelUsuario = new javax.swing.JPanel();
        ver = new javax.swing.JButton();
        conectandotxt = new javax.swing.JLabel();
        progreso = new javax.swing.JProgressBar();
        logouser = new javax.swing.JLabel();
        circulouser = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usuariotxt = new javax.swing.JTextField();
        IngresarBtn = new javax.swing.JButton();
        contratxt = new javax.swing.JPasswordField();
        iniciarsesion = new javax.swing.JLabel();
        iconousuario = new javax.swing.JLabel();
        iconoconstra = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        cerrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrar");
        setIconImage(getIconImage());
        setUndecorated(true);
        setResizable(false);

        PanelUsuario.setName(""); // NOI18N
        PanelUsuario.setOpaque(false);
        PanelUsuario.setPreferredSize(new java.awt.Dimension(600, 600));
        PanelUsuario.setLayout(null);

        ver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ver.png"))); // NOI18N
        ver.setBorder(null);
        ver.setBorderPainted(false);
        ver.setContentAreaFilled(false);
        ver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ver.setDefaultCapable(false);
        ver.setFocusPainted(false);
        ver.setFocusable(false);
        ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verActionPerformed(evt);
            }
        });
        PanelUsuario.add(ver);
        ver.setBounds(300, 250, 40, 30);

        conectandotxt.setForeground(new java.awt.Color(255, 255, 255));
        conectandotxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        conectandotxt.setText("Conectando ...");
        PanelUsuario.add(conectandotxt);
        conectandotxt.setBounds(40, 360, 310, 20);
        PanelUsuario.add(progreso);
        progreso.setBounds(0, 360, 400, 20);

        logouser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logouser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-administrador-del-hombre-100.png"))); // NOI18N
        PanelUsuario.add(logouser);
        logouser.setBounds(155, 7, 80, 90);

        circulouser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        circulouser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/120px-PETER-RIVER.png"))); // NOI18N
        PanelUsuario.add(circulouser);
        circulouser.setBounds(135, 0, 118, 118);
        circulouser.getAccessibleContext().setAccessibleDescription("");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user.png"))); // NOI18N
        PanelUsuario.add(jLabel1);
        jLabel1.setBounds(54, 180, 30, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-candado-2-filled-20.png"))); // NOI18N
        PanelUsuario.add(jLabel2);
        jLabel2.setBounds(60, 245, 20, 40);

        usuariotxt.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        usuariotxt.setForeground(new java.awt.Color(72, 124, 162));
        usuariotxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usuariotxt.setText("Usuario");
        usuariotxt.setToolTipText("");
        usuariotxt.setBorder(null);
        usuariotxt.setOpaque(false);
        usuariotxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usuariotxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usuariotxtFocusLost(evt);
            }
        });
        PanelUsuario.add(usuariotxt);
        usuariotxt.setBounds(90, 180, 240, 40);

        IngresarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_ingrear.png"))); // NOI18N
        IngresarBtn.setToolTipText("");
        IngresarBtn.setBorder(null);
        IngresarBtn.setBorderPainted(false);
        IngresarBtn.setContentAreaFilled(false);
        IngresarBtn.setDefaultCapable(false);
        IngresarBtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_ingrear.png"))); // NOI18N
        IngresarBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_ingrear.png"))); // NOI18N
        IngresarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarBtnActionPerformed(evt);
            }
        });
        PanelUsuario.add(IngresarBtn);
        IngresarBtn.setBounds(120, 310, 170, 40);

        contratxt.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        contratxt.setForeground(new java.awt.Color(72, 124, 162));
        contratxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        contratxt.setText("Contraseña");
        contratxt.setBorder(null);
        contratxt.setOpaque(false);
        contratxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                contratxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                contratxtFocusLost(evt);
            }
        });
        PanelUsuario.add(contratxt);
        contratxt.setBounds(91, 245, 210, 40);

        iniciarsesion.setFont(new java.awt.Font("Chaparral Pro Light", 3, 48)); // NOI18N
        iniciarsesion.setForeground(new java.awt.Color(255, 255, 255));
        iniciarsesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iniciarsesion.setText("Iniciar Sesion");
        iniciarsesion.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                iniciarsesionMouseDragged(evt);
            }
        });
        iniciarsesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                iniciarsesionMousePressed(evt);
            }
        });
        PanelUsuario.add(iniciarsesion);
        iniciarsesion.setBounds(70, 120, 250, 60);

        iconousuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/txt_grande.png"))); // NOI18N
        PanelUsuario.add(iconousuario);
        iconousuario.setBounds(50, 180, 290, 40);

        iconoconstra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/txt_grande.png"))); // NOI18N
        PanelUsuario.add(iconoconstra);
        iconoconstra.setBounds(50, 245, 290, 40);

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        PanelUsuario.add(fondo);
        fondo.setBounds(0, 60, 400, 300);

        cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar_44.png"))); // NOI18N
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
        });
        PanelUsuario.add(cerrar);
        cerrar.setBounds(310, 0, 90, 60);

        getContentPane().add(PanelUsuario, java.awt.BorderLayout.PAGE_START);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarsesionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciarsesionMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_iniciarsesionMousePressed

    private void iniciarsesionMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciarsesionMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_iniciarsesionMouseDragged

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_cerrarMouseClicked

    private void IngresarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarBtnActionPerformed
        if ( "Rivoin".equals( usuariotxt.getText() ) && "123".equals( contratxt.getText() ) ) {
            UsuarioExiste = 1 ;
            progreso.setVisible(true);
            conectandotxt.setVisible(true);
            timer.start();
            usuariotxt.setEnabled(false);
            contratxt.setEnabled(false);            
        }
    }//GEN-LAST:event_IngresarBtnActionPerformed

    private void usuariotxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usuariotxtFocusGained
        if ( usuariotxt . getText () . trim() . equals ( "Usuario" ) ) {
            usuariotxt.setText ("");
            usuariotxt.setForeground (new Color(0,64,255));
        }
    }//GEN-LAST:event_usuariotxtFocusGained

    private void usuariotxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usuariotxtFocusLost
        if ( usuariotxt . getText (). trim (). equals ("") ) {
            usuariotxt.setText ("Usuario");
            usuariotxt.setForeground (new Color (72,124,162));
        }
    }//GEN-LAST:event_usuariotxtFocusLost

    private void contratxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contratxtFocusGained
        
        if ( contratxt . getText () . trim() . equals ( "Contraseña" ) && VerContra == 0 ) {
            contratxt.setEchoChar('*');
            contratxt.setText ("");
            VerContra = 1 ;
            contratxt.setForeground (new Color(0,64,255));
        }
    }//GEN-LAST:event_contratxtFocusGained

    private void contratxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contratxtFocusLost
        if ( contratxt . getText (). trim (). equals ("") && VerContra == 1 ) {
            contratxt.setEchoChar( ( char ) 0 );
            contratxt.setText ("Contraseña");
            VerContra = 0 ;
            contratxt.setForeground (new Color (72,124,162)); 
        }
    }//GEN-LAST:event_contratxtFocusLost

    private void verActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verActionPerformed
        if ( VerIconoContra == 0 ) {
            VerIconoContra = 1 ;
            ver.setIcon( new ImageIcon("src/Imagenes/verNo.png"));
            contratxt.setEchoChar( ( char ) 0 );
        } else if ( VerIconoContra == 1 ) {
            contratxt.setEchoChar('*');
            VerIconoContra = 0 ;
            ver.setIcon( new ImageIcon("src/Imagenes/ver.png"));
        }
    }//GEN-LAST:event_verActionPerformed

      
    public class CargandoBarra implements ActionListener{

        public void actionPerformed(ActionEvent ae) {
            conectandotxt.setBackground(Color.BLUE);
            int a = progreso.getValue();
            if ( a < 100 ) {
                a++ ;
                progreso.setValue(a);
                conectandotxt.setText(" Conectando ... " + a + " % "); 
            } else if ( a >= 100 ) {
                timer.stop();                
                conectandotxt.setText(" Conexion establecida ");
                
                dispose();
                FormularioPersonalizado nuevo = new FormularioPersonalizado();
                nuevo.setVisible(true);
            }
            
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (Exception e) {
                }
                new Login().setVisible(true);            
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IngresarBtn;
    private javax.swing.JPanel PanelUsuario;
    private javax.swing.JLabel cerrar;
    private javax.swing.JLabel circulouser;
    private javax.swing.JLabel conectandotxt;
    private javax.swing.JPasswordField contratxt;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel iconoconstra;
    private javax.swing.JLabel iconousuario;
    private javax.swing.JLabel iniciarsesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel logouser;
    private javax.swing.JProgressBar progreso;
    private javax.swing.JTextField usuariotxt;
    private javax.swing.JButton ver;
    // End of variables declaration//GEN-END:variables
}
